### ISSUE TITLE
Simplify terminology Period and draws

### ISSUE THREAD

**Issue by SjoenH** [miles-no/miles_kabinizer#96]
Terminology is confusing.

Look into what a "draw" really is and suggest a refactor.

**Comment by SjoenH** [comment]
Maybe rename `draw` to a deadline? Or maybe get rid of the `draw` table altogether?

**Comment by wigsnes** [comment]
I think draw is a good name, Maybe if we are more specific on the other words like period can be **StayPeriod**. And a user register their desired staysPeriods as a **Registration**. And we have **Allocations** for what stayPeriods a user have been given.

**Comment by SjoenH** [comment]
Yeah... maybe. Thanks for the input. 👍  I'm putting this on hold for a while.
